#!/bin/sh

# Fancy bookmarking system with terminal and browser interfaces.
# Copyright (C) 2019  Karmjit Mahil
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

SCRIPT_NAME=`basename $0`
readonly SCRIPT_NAME
ECHO_HELP="Try '$SCRIPT_NAME --help' for more information."
readonly ECHO_HELP

# Config file only contains the path to db for now.
# Config file is deleted when db is deleted, otherwise 'database not fond' error will be shown
CFG_FILE="$HOME/.config/$SCRIPT_NAME/${SCRIPT_NAME}"
CFG_FOLDER=`dirname $CFG_FILE`
if [ ! -e "$CFG_FILE" ]; then
	if [ "$1" = "init" ]; then
		if [ "$(echo $2 | cut -c 1)" != "/" ]; then
			echo "Please use a full path."
			exit 1
		fi

		if [ ! -d "$CFG_FOLDER" ]; then
			mkdir "$CFG_FOLDER"
		fi

		touch "$2"
		echo "Database created: $2"
		echo "DB_LOCATION $2" > "$CFG_FILE"
	else
		echo "Database is not initialised."
		echo "To initialise the database: '$SCRIPT_NAME init path'."
		echo "Where 'path' is the file path to the database."
	fi
	exit
else
	DB=`cat $CFG_FILE 2> /dev/null | awk '/DB_LOCATION/ { print $2 }'`
	if [ ! "$DB" ]; then
		echo "Error in configuration file: $CFG_FILE"
		exit 1
	fi
	readonly DB

	if [ ! -e "$DB" ]; then
		echo "${SCRIPT_NAME}: database not found: $DB"
		exit 1
	fi
fi

help() {
	echo "Usage: $SCRIPT_NAME"
	echo "\t-                       Read from standard input."
	echo "\t-a | --add url          Add a url."
	echo "\t-d | --delete id        Delete url with ID."
	echo "\t-D | --delete-db        Delete database."
	echo "\t-l | --list-all         List all urls saved."
	echo "\t          "
	exit
}

add() {
	# Basic url validation
	echo "$1" | grep -q  -E "https?://[0-9A-Za-z]+\..+"
	if [ $? -eq 1 ]; then
		echo "$1: Not a url."
		exit 1
	fi

	cat "$DB" | awk '{ print $2 }' | grep -q "^$1\$"
	if [ $? -eq 0 ]; then
		echo "$1: Already saved."
		exit
	fi

	# ID of first item added is 1
	LAST_ID=`tail -n 1 "$DB" | awk '{ print $1 }'`
	LAST_ID="${LAST_ID:-0}"
	ID=`expr $LAST_ID + 1`
	echo "${ID} $1" >> $DB
}

deleteUrl() {
	# Checks if $1 is an integer.
	echo "$1" | grep -q '^[0-9]*$'
	if [ "$?" = 0 ]; then
		TEXT=`sed "/^${1} ./d" $DB`
		# -n required as /n causes problems if all urls are deleted.
		echo -n "$TEXT" > $DB
	else
		echo "$1: Not an ID."
		exit 1
	fi
}

printUrls() {
	if [ -s $DB ]; then
		cat "$DB" | awk -F " " 'BEGIN { print "ID\tURL"} { print $1 "\t" $2}'
	else
		echo "No entries."
	fi
}

if [ $# -eq 0 ]; then
	help
	exit
fi

READ_STDIN=false
if [ "$1" = "-" ]; then
	READ_STDIN=true
	shift
fi

while [ -n "$(echo $1 | grep '-')" ]; do
	case $1 in
		-h|--help)
			help
			exit
			;;

		-a|--add)
			if [ $2 ]; then
				add $2
				shift
			elif $READ_STDIN ; then
				add $(cat /proc/${$}/fd/0)
			else
				echo "No url specified."
				exit 1
			fi
			;;
		-d|--delete)
			if [ $2 ]; then
				deleteUrl "$2"
				shift
			fi
			;;
		-D|--delete-db)
			echo "The database will be deleted."
			echo "Do you wish to continue (y/n): "
			read RESPONSE
			echo $RESPONSE | grep -q '^[yY]'
			if [ "$?" = 1 ]; then
				exit 0
			fi

			rm $DB
			rm $CFG_FILE
			echo "Database deleted."
			;;
		-l|--list-all)
			printUrls
			exit
			;;
		*)
			echo "$SCRIPT_NAME: $OPTION: no such option."
			echo "$ECHO_HELP"
			exit
			;;
	esac
	shift
done
