#!/bin/sh
# This script is self sufficient and can be run on its own to setup the application

APP_NAME=${APP_NAME:-"troshure"}

CFG_FILE=${CFG_FILE:-"$HOME/.config/$APP_NAME/$APP_NAME"}

CFG_FOLDER=`dirname $CFG_FILE`
if [ ! -d "$CFG_FOLDER" ]; then 
	mkdir "$CFG_FOLDER" 
fi 

DEF_DB_NAME="websites"
readonly DEF_DB_NAME

if [ "$1" = "-h" -o "$1" = "--help" ]; then
	echo "Usage: $(basename $0) [FILE-PATH]"
	echo "If not parameters are given or a folder's path is given, the database file will be created in the current directory or specified directory with name '$DEF_DB_NAME'."
	exit 0
fi

if [ ! "$1" ]; then
	DB=`echo "$(pwd)/${DEF_DB_NAME}"`
else
	# Not sue if realpath is present on Mac systems.
	DB=`realpath "$1"`
	if [ -d "$DB" ]; then
		DB="$DB/$DEF_DB_NAME"
	fi
fi

# Creating DB file
touch "$DB"
echo "Database created: $DB"
echo "DB $DB" > "$CFG_FILE"

# Set command to open urls
URL_OPEN_CMD="xdg-open"
which "$URL_OPEN_CMD" >/dev/null 2>&1
if [ "$?" -ne 0 ]; then
        # On a Mac, instead of xdg-open, open is used.
        URL_OPEN_CMD="open"
fi
echo "URL_OPEN_CMD $URL_OPEN_CMD" >> "$CFG_FILE"
