#!/bin/sh

SCRIPT_NAME=`echo $0 | sed "s_/_\n_g" | tail -n 1`

# Line number used as id for an entry. Starts from 0.
DB=$HOME/sites
SEPARATOR=" "

help() {
	echo "Usage: $SCRIPT_NAME [-] [-a url]"
	echo "\t-\tRead from standard input."
	echo "\t-a\tAdd a url."
	exit
}

add() {
	# Basic url validation
	echo $1 | grep -q  -E "https?://[0-9A-Za-z]+\..+"
	if [ $? -eq 1 ]; then
		echo "$1: Not a url."
		exit 1
	fi

	# Line number used as id. Starts from 0
	ID=`wc -l $DB | awk -F " " "{ print $ 1 }"`

	echo "$ID$SEPARATOR$1" >> $DB
}

# Create list file if non existent.
if [ ! -e $DB ]; then
	touch $DB
fi

if [ $# -eq 0 ]; then
	help
fi

READ_STDIN=false
if [ $1 = "-" ]; then
	READ_STDIN=true
	shift
fi

while [ -n "$(echo $1 | grep '-')" ]; do
	case $1 in
		-h)
			help
			;;
		--help)
			help
			;;
		-a)
			if [ $2 ]; then
				add $2
				shift
			elif [ "$READ_STDIN" = true ]; then
				add $(cat /proc/${$}/fd/0)
			else
				echo "No url specified."
				exit 1
			fi
			;;
		*)
			echo "$SCRIPT_NAME: $OPTION: no such option."
			exit
			;;
	esac
	shift
done
