#!/bin/sh

SCRIPT_NAME=`echo $0 | sed "s_/_\n_g" | tail -n 1`
DB=$HOME/sites

help() {
	echo "Usage: $SCRIPT_NAME [-a url]"
}

# Create list file if non existent.
if [ ! -e $DB ]; then
	touch $DB
fi

# If no parameter is given when executing.
if [ $1 ]; then
	OPTION=$1
else
	OPTION="-h"
fi

case $OPTION in
	-h)
		help
		break
		;;
	--help)
		help
		break
		;;
	-a)
		add
		break
		;;
	*)
		echo "$SCRIPT_NAME: $OPTION: no such option."
		;;
esac
